### ISSUE TITLE
Reconnecting after a disconnect due to a broken network link

### ISSUE THREAD

**Issue by scottpidzarko** [jchristn/SuperSimpleTcp#100]
I am noticing some weird behaviour after reconnecting to a server with an existing socket - the Disconnect event fires multiple times and sometimes the .IsConnected property doesn't reflect the actual state.

Per the discussion in #12 - do we still have to dispose the client object after each disconnect when KeepAlives are enabled? That discussion was back in 2020.

**Comment by jchristn** [comment]
Hi @scottpidzarko what is causing the disconnect event to fire multiple times?  Are you experiencing a disconnect in the network or manually calling ```Disconnect```?

You should not have to ```Dispose``` before calling ```Connect``` again.  Whether keepalives are enabled or not should not matter.  Here you can see example where I connect with the client, send some data, call ```Disconnect```, then ```Connect```, and then send more data.

![image](https://user-images.githubusercontent.com/1421081/143053021-b044e09d-0686-4b48-abdb-43a805c53ab4.png)

**Comment by scottpidzarko** [comment]
Thanks for your prompt response.

I was experiencing a disconnect in the network (for whatever reason) and loosing connection between the client and server. I then was purposely triggering it by shutting down the network port the server was connected to in order to figure out what was going on. 

I'll try to find some time today or tomorrow to follow up with what I was doing to produce this issue and post sample code that shows the issue.

**Comment by jchristn** [comment]
Which operating system and runtime are you using?  I've noticed some strange behavior with keepalives - they are operated/managed by the underlying operating system and not the library.  It might be best *not* to use them, and instead, send your own application-level heartbeat messages on a regular basis to validate connectivity.
