### ISSUE TITLE
sometimes System.NullReferenceException on send or SendAsync happend

### ISSUE THREAD

**Issue by mzelecom** [jchristn/SuperSimpleTcp#101]
hi .
i dont lnow why sometimes i get this error.when call send or SendAsync.and data not send.

An exception of type 'System.NullReferenceException' occurred in soft.exe but was not handled in user code
Additional information: Object reference not set to an instance of an object.

**Comment by jchristn** [comment]
Hi @mzelecom could you wrap your ```Send``` and ```SendAsync``` calls in a try/catch, serialize the exception, and paste here?
