### ISSUE TITLE
If the same "Events_ClientConnected" is connected in multi-server expansion, can you add the information to which IpPort address it is connected to?

### ISSUE THREAD

**Issue by saklanmaz** [jchristn/SuperSimpleTcp#102]
Hello,

I need to create server in different ports in my project. Example; 192.168.1.1:20, 192.168.1.1:21,192.168.1.1:22 . 

Instead of creating a new "Events_ClientConnected" function for each server, I want to assign them all to one function. The same is true for Events_ClientDisconnected. Knowing which server port these events occur for will greatly reduce the number of lines of code to be written.

Is it possible to add such a feature?

**Comment by jchristn** [comment]
Hi @saklanmaz 

It should already be doing this for both connection events (see https://github.com/jchristn/SuperSimpleTcp/blob/772870baa0ed9757deaa934e8f33dc8c6693d5cb/SimpleTcp/SimpleTcpClient.cs#L322) and disconnection events (see https://github.com/jchristn/SuperSimpleTcp/blob/772870baa0ed9757deaa934e8f33dc8c6693d5cb/SimpleTcp/SimpleTcpClient.cs#L686).

Are you seeing the ```ClientConnected``` or ```ClientDisconnected``` events fire without ```args.IpPort``` being set?  If so under which conditions?

**Comment by saklanmaz** [comment]
Thank you for answer. I'm confused on how to implement it. Can you please help?

The function I created the link is as follows.

```
public bool Connect(SimpleTcpServer simpleTcpServer)
        {
            try
            {
                simpleTcpServer.Events.ClientConnected += Events_ClientConnected;
                simpleTcpServer.Events.ClientDisconnected += Events_ClientDisconnected;
                simpleTcpServer.Events.DataReceived += Events_DataReceived;
                simpleTcpServer.Start();

                return simpleTcpServer.IsListening;
            }
            catch
            {
                return false;
            }
        }
```

I am sharing the sample function for ClientConnected.

```

Here I can access the IP and Port of the connected Client address. What server IpPort the Client I want to access is connected to.

private void Events_ClientConnected(object sender, ClientConnectedEventArgs e)
{
            Console.WriteLine(e.IpPort);
}
```

**Comment by jchristn** [comment]
The ```ClientConnected``` and ```ClientDisconnected``` event's ```EventArgs``` has a property called ```IpPort```.  On client events, ```IpPort``` contains the IP:port of the server.  Is that not what you are experiencing?

**Comment by saklanmaz** [comment]
e.IpPort is the IpPort of the connecting client, not the server?

**Comment by jchristn** [comment]
```e.IpPort``` is for the server when used in client events.

![image](https://user-images.githubusercontent.com/1421081/149357613-ab46f7ae-e207-443b-80e0-24523ff8f938.png)

Client events:
```
        static void Connected(object sender, ClientConnectedEventArgs e)
        {
            Console.WriteLine("*** Server " + e.IpPort + " connected");
        }

        static void Disconnected(object sender, ClientDisconnectedEventArgs e)
        {
            Console.WriteLine("*** Server " + e.IpPort + " disconnected"); 
        }
```

**Comment by jchristn** [comment]
I'm going to release v2.5 momentarily just for this - I think the comments/documentation on the event arguments object are misleading.  But, it is a small breaking change.  ```ClientConnectedEventArgs``` and ```ClientDisconnectedEventArgs``` will just become ```ConnectionEventArgs```.

**Comment by jchristn** [comment]
Please confirm that ```e.IpPort```, when inside your client connect/disconnect event, is the IP:port of the server.  Thanks!

**Comment by saklanmaz** [comment]
Thanks for be interested. So what can we do to access the IpPort of both the server and the client together? It will make more sense if I explain what I actually want to do.

I provide support for opening more than one server in the same user interface. I keep connecting clients in a list. I want to detect from which server the incoming data comes from the client. I show only that data according to the server and client that the user selects in the list. Therefore, accessing both server and client IpPort in the same interrupt will greatly increase my functionality.

**Comment by jchristn** [comment]
I can expose ```IPEndPoint``` from ```SimpleTcpClient``` (see NuGet v2.5.0.1 [here](https://www.nuget.org/packages/SuperSimpleTcp/2.5.0.1)) however I think that's not the right approach for your use case.

Instead of a list, I would use ```Dictionary<string, SimpleTcpClient>```, where the key is the IP:port of the server.  You can then retrieve the client through ```dict["192.168.0.15"];``` where ```192.168.0.15``` is the server IP.

**Comment by saklanmaz** [comment]
I am currently using the way you mentioned. Knowing in cutting seemed to make things easier though. Thank you for the change.

**Comment by saklanmaz** [comment]
I installed the nuget package. However, not in the way I expected. I think I'm explaining myself wrong.

 ```
private void Events_ClientDisconnected(object sender, ConnectionEventArgs e)
        {
            try
            {
                var serverIpPort  = e.ServerIpPort;
                var clientIpPort = e.ClientIpPort;
            }
            catch { }
        }
```

Actually, I'm wondering if something like this is possible in my application. Is it possible to access both the server IpPort and the IpPort of the clients that connect or want to disconnect in server interruptions?

**Comment by jchristn** [comment]
The ```object sender``` is always ```SimpleTcpClient```.  There's a public property you can access called ```IPEndPoint LocalEndpoint```, and from within there, you can access the local port information.

**Comment by saklanmaz** [comment]
Thank you @jchristn for answer. :)
