### ISSUE TITLE
EventWaitHandler error in SimpleTcpClient/Connect()

### ISSUE THREAD

**Issue by oprivat** [jchristn/SuperSimpleTcp#106]
Using the SimpleTcpClient object and it's public method 'Connect()' found an unhandled error (only with .NET6.0).
The method can typically throw two types of errors:

- timeout error after the BeginConnect(...).Waitone
- socket error after the EndConnect()

The timeout error may be thrown if the remote sever address cannot be accessed. If the WaitHandle is closed an new error is raised . I believe that the WaitOne has received a signal and the WaitHandler cannot be closed.

After the socket error the WaitHandle can be closed.

I am using SimpleTcpClient in a workerservice and the unhandled error would stop my service.

I have resolved the issue and can profide the new Connect() method.

**Comment by jchristn** [comment]
Hi @oprivat which version were you using?  I recently addressed an issue of this kind in the latest version.  If your fix is for the latest version I'd love to see it.  Thanks so much

**Comment by oprivat** [comment]
Hi @jchristn 
I updated to version 2.5.0.1, and still had the issue.
Hence I modified code in what I believe is the latest version...
Have alook below at the only change made in the Connect() method (in SimpleTcpClient).

Regards.

**_public void Connect()
        { 
            if (IsConnected)
            {
                Logger?.Invoke(_Header + "already connected");
                return;
            }
            else
            {
                Logger?.Invoke(_Header + "initializing client");

                InitializeClient(_Ssl, _PfxCertFilename, _PfxPassword);

                Logger?.Invoke(_Header + "connecting to " + ServerIpPort);
            }

            _TokenSource = new CancellationTokenSource();
            _Token = _TokenSource.Token;

            IAsyncResult ar = _Client.BeginConnect(_ServerIp, _ServerPort, null, null);
            WaitHandle wh = ar.AsyncWaitHandle;

            try
            {
                if (!ar.AsyncWaitHandle.WaitOne(TimeSpan.FromMilliseconds(_Settings.ConnectTimeoutMs), false))
                {
                    _Client.Close();
                    throw new TimeoutException("Timeout connecting to " + ServerIpPort);
                }

                _Client.EndConnect(ar);
                _NetworkStream = _Client.GetStream();

                if (_Ssl)
                {
                    if (_Settings.AcceptInvalidCertificates)
                        _SslStream = new SslStream(_NetworkStream, false, new RemoteCertificateValidationCallback(AcceptCertificate));
                    else
                        _SslStream = new SslStream(_NetworkStream, false);

                    _SslStream.AuthenticateAsClient(_ServerIp, _SslCertCollection, SslProtocols.Tls12, !_Settings.AcceptInvalidCertificates);

                    if (!_SslStream.IsEncrypted) throw new AuthenticationException("Stream is not encrypted");
                    if (!_SslStream.IsAuthenticated) throw new AuthenticationException("Stream is not authenticated");
                    if (_Settings.MutuallyAuthenticate && !_SslStream.IsMutuallyAuthenticated) throw new AuthenticationException("Mutual authentication failed");
                }

                if (_Keepalive.EnableTcpKeepAlives) EnableKeepalives();
            }
            //Exception add by OP 17/01/2022 for v2.5.0.2
            //The Timeout Exception is generated by the WaitOne asyncWaitHandle. When that happens the WaitHandle cannot be closed (already signaled).
            //The Socket Exception is generated by the EndConnect() method. The WaitHandle can be closed as it has been signaled already.
            catch (TimeoutException t) 
            {
                throw t;
            }
            catch (SocketException s)
            {
                wh.Close();
                throw s;
            }
            //
           _IsConnected = true;
            _LastActivity = DateTime.Now;
            _IsTimeout = false;
            _Events.HandleConnected(this, new ConnectionEventArgs(ServerIpPort));
            _DataReceiver = Task.Run(() => DataReceiver(_Token), _Token);
            _IdleServerMonitor = Task.Run(() => IdleServerMonitor(), _Token);
        }_**

**Comment by jchristn** [comment]
Hi @oprivat could you try v2.5.0.2?  I fixed this issue in that version (see https://github.com/jchristn/SuperSimpleTcp/commit/67f574b4c40f7031b4ca5c38c9626274573c7c68)

**Comment by oprivat** [comment]
@jchristn 
Yeah, you version v2.5.0.2 works fine and has resolved the issue. Please note that you don't need the following line (in Connect() method):
_WaitHandle wh = ar.AsyncWaitHandle; //can be removed_

And just a comment but in the ClientTest project, you should handle exceptions. But that's doesn't affect your package.

Thanks a lot
