### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by AlonHertzog** [jchristn/SuperSimpleTcp#107]
Hey,
I am using this nuget for tcp connection between two local computers, In .NET 4.6.
When I am using ConnectWithRetries, I get a connection, disconnection eent and after is a stable connect.
![image](https://user-images.githubusercontent.com/69188431/150085891-23af6ca6-4695-4942-aaa9-122845a4d961.png)

**Comment by oprivat** [comment]
@AlonHertzog
You may want to indicate if your log sample is from the TCPServer or from the TCPClient.
Then you will have to test your TcpServer code using a standard Tcp terminal. Then test your TcpClient code using a standard Tcp server.
When using ConnectWithRetries from the SuperSimpleTcp Client it tries to connect asynchronuously until it succeed or until a set timeout has expired. Each attempt is timed out by a hardcoded 1s delay. Maybe at your first attempt it takes more than 1 s. for the server to accept the incoming connection...
