### ISSUE TITLE
System.ObjectDisposedException on a WPF Application (.NET 6)

### ISSUE THREAD

**Issue by tinohager** [jchristn/SuperSimpleTcp#108]
Hi

I have upgraded my Application to .NET 6, but when I try to connect a non-existing host i run in this exception `ObjectDisposedException`

![ObjectDisposedException](https://user-images.githubusercontent.com/8215186/150215841-17a4d00f-e05f-4db4-b142-0f9682e6c1cb.png)

My test code
```cs
private void Button_Click(object sender, RoutedEventArgs e)
{
    try
    {
        var client = new SimpleTcpClient("192.168.0.50", 1234);
        client.Connect();
    }
    catch (Exception exception)
    {

    }
}
```

The cause of the error must be somewhere here, but the error only occurs with the current .NET 6 version

https://github.com/jchristn/SuperSimpleTcp/blob/c17dccec8a4e82d5a5f1d5317a864a241051f28b/SimpleTcp/SimpleTcpClient.cs#L330-L333

**Comment by jchristn** [comment]
Hi @tinohager could you try with [v2.5.0.2](https://www.nuget.org/packages/SuperSimpleTcp/2.5.0.2)?

**Comment by tinohager** [comment]
@jchristn Without this line it works the call is not needed?

**Comment by jchristn** [comment]
Hi, yes, I just removed that in v2.5.0.2 :) could you try it?

**Comment by tinohager** [comment]
now it works

**Comment by jchristn** [comment]
Excellent!  Thanks @tinohager
