### ISSUE TITLE
Issue with Connect() immediately after Disconnect()

### ISSUE THREAD

**Issue by powerzone3000** [jchristn/SuperSimpleTcp#110]
I am facing an issue when I'm `Disconnect()`ing from a server and try to reconnect immediately.

The Server I'm connecting to sends a heartbeat every 5 seconds. If no heartbeat is received for more than 5 seconds (plus some grace period), I want to renew the connection by doing 
```
client.Disconnect(); // because IsConnected is still true
client.Connect();
```
which gives me the following output
```
[SimpleTcp.Client] disconnecting from 127.0.0.1:8000
[SimpleTcp.Client] initializing client
[SimpleTcp.Client] connecting to 127.0.0.1:8000
Event Connected
[SimpleTcp.Client] data receiver canceled, peer disconnected
Event Disconnected, e.Reason: Normal
[SimpleTcp.Client] dispose complete
[SimpleTcp.Client] data receiver canceled, peer disconnected
Event Disconnected, e.Reason: Normal
[SimpleTcp.Client] dispose complete
```

This seems like a timing/synchronization problem.

I can work around it by putting a `Thread.Sleep(500);` after the `client.Disconnect();`, but that's probably not the most reliable solution.

Is there a better way?

**Comment by jchristn** [comment]
Hi @powerzone3000 sorry for the delay.  Yes, it appears that the effect of ```_TokenSource.Cancel()``` isn't complete prior to releasing control back to your code.

I've added a fix for this in v2.5.0.4, now going to NuGet.  Could you test and let me know if it works?

Thanks!

**Comment by powerzone3000** [comment]
Thank you for your response @jchristn. Unfortunately, the behavior is still the same for me.

**Comment by jchristn** [comment]
> Thank you for your response @jchristn. Unfortunately, the behavior is still the same for me.

That's a bummer.  Looking again.

**Comment by jchristn** [comment]
Hi @powerzone3000 could you try with v2.6.0.2?  Please re-open if any issues.

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.6.0.2
Commit: https://github.com/jchristn/SuperSimpleTcp/commit/66b3893f78f11953bc11c53917d232af6ad0fdb4

**Comment by powerzone3000** [comment]
Yup, it works now. Thanks a lot!
