### ISSUE TITLE
Align namespaces with project

### ISSUE THREAD

**Issue by tinohager** [jchristn/SuperSimpleTcp#119]
Hi the project always use `SimpleTcp` as Namespace can i rename it to the new project name `SuperSimpleTcp` then everything would come together again. That would be a breaking change, of course.

**Comment by tinohager** [comment]
Also I would like to introduce a src folder
similar to here ... https://github.com/nager/Nager.Date

**Comment by jchristn** [comment]
Hi @tinohager please feel free!

**Comment by tinohager** [comment]
I always use the same structure for my own projects (https://github.com/nager)

```
.
├── doc                    # Documentation files (alternatively `doc`)
├── src                     # Source files (alternatively `lib` or `app`)
├── LICENSE.md
└── README.md
```

There is no one guide to this topic. But across multiple sources, the suggestion is always the scr folder and a doc/docs folder.
- https://github.com/kriasoft/Folder-Structure-Conventions
- https://soulaimanghanem.medium.com/github-repository-structure-best-practices-248e6effc405
- https://coderefinery.github.io/reproducible-research/02-organizing-projects/

**Comment by jchristn** [comment]
This is very helpful, thank you again!
