### ISSUE TITLE
client  `Disconnect ` method  blocking issue in 2.6.x

### ISSUE THREAD

**Issue by czyt** [jchristn/SuperSimpleTcp#129]
hello, I use nuget pkg 2.5.x in a wpf prism project,worked well.
however when I upgarded to 2.6.x to the latest 2.6.x version.the client  `Disconnect ` method seems to blocking main thread.so I wonder if there were some changes in logic in the new version.

2.6 client code via dnspy
```csharp
public void Disconnect()
{
	if (this.IsConnected)
	{
		Action<string> logger = this.Logger;
		if (logger != null)
		{
			logger(this._header + "disconnecting from " + this.ServerIpPort);
		}
		this._tokenSource.Cancel();
		this._dataReceiver.Wait();
		this._client.Close();
		this._isConnected = false;
		return;
	}
	Action<string> logger2 = this.Logger;
	if (logger2 == null)
	{
		return;
	}
	logger2(this._header + "already disconnected");
}
```
2.5.4 client code via dnspy
```csharp
public void Disconnect()
{
	if (this.IsConnected)
	{
		Action<string> logger = this.Logger;
		if (logger != null)
		{
			logger(this._Header + "disconnecting from " + this.ServerIpPort);
		}
		this._TokenSource.Cancel();
		this._TokenSource.Token.WaitHandle.WaitOne();
		this._Client.Close();
		this._IsConnected = false;
		return;
	}
	Action<string> logger2 = this.Logger;
	if (logger2 == null)
	{
		return;
	}
	logger2(this._Header + "already disconnected");
}
```

**Comment by jchristn** [comment]
Hi, yes, the issue with 2.5 was that ```Disconnect``` would return prior to the cancellation actually happening, so if you attempt to ```Start``` again, it would fail (in glorious fashion).  The ```.Wait()``` was added to the ```DataReceiver``` task to make sure it had actually terminated prior to allowing ```Disconnect``` to return.

**Comment by czyt** [comment]
> Hi, yes, the issue with 2.5 was that `Disconnect` would return prior to the cancellation actually happening, so if you attempt to `Start` again, it would fail (in glorious fashion). The `.Wait()` was added to the `DataReceiver` task to make sure it had actually terminated prior to allowing `Disconnect` to return. If you want, you can always fire an unawaited task in your code to do this, i.e. `Task.Run(() => client.Disconnect());`

thanks for your reply!

**Comment by Antix-Development** [comment]
I don;t know if it is the same issue but with 3.0.10 if I call `client.Disconnect()` my client application freezes.
Using the fix `Task.Run(() => client.Disconnect());` causes the client application to disconnect correctly.

If it is the same issue, will there be a time when the `Task.Run()` fix isn't required?

If not maybe it could be added in the readme so it's more obvious than having to search closed issues :)

Great system BTW, very easy to get up and running with it.

**Comment by jchristn** [comment]
Hi @Antix-Development thanks for your kind words.  Is this something you can reproduce regularly?  I haven't been able to do so with the test projects.  Cheers, Joel

**Comment by jchristn** [comment]
Ah, yes, winforms :) it gets tricky with winforms.  I'm not an expert, but I have experienced interaction with objects blocking the main thread in a forms app.  Probably best to have it in a background task.
