### ISSUE TITLE
SimpleTcpClient doesn't detect when client has been disconnected from the server

### ISSUE THREAD

**Issue by IanPNewson** [jchristn/SuperSimpleTcp#130]
Hi, I had an issue where I was using the Disconnected event to attempt a reconnection. However this event doesn't fire when I close the server, even though I had the following code in my own Dispose:

```
    public override void Dispose()
    {
        base.Dispose();

        foreach (var client in _server.GetClients())
            _server.DisconnectClient(client);

        _server.Dispose();
    }
```
I fixed this by adding a check in the DataReadAsync method of SimpleTcpClient:

```
            try
            {
                if (!_ssl)
                {
                    read = await _networkStream.ReadAsync(buffer, 0, buffer.Length, token).ConfigureAwait(false);
                }
                else
                {
                    read = await _sslStream.ReadAsync(buffer, 0, buffer.Length, token).ConfigureAwait(false);
                }

                if (read > 0)
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        ms.Write(buffer, 0, read);
                        return ms.ToArray();
                    }
                }
                else
                {
//addition start
                    IPGlobalProperties ipProperties = IPGlobalProperties.GetIPGlobalProperties();
                    TcpConnectionInformation[] tcpConnections = ipProperties.GetActiveTcpConnections()
                        .Where(x => x.LocalEndPoint.Equals(this._client.Client.LocalEndPoint) && x.RemoteEndPoint.Equals(this._client.Client.RemoteEndPoint)).ToArray();

                    var isOk = false;

                    if (tcpConnections != null && tcpConnections.Length > 0)
                    {
                        TcpState stateOfConnection = tcpConnections.First().State;
                        if (stateOfConnection == TcpState.Established)
                        {
                            isOk = true;
                        }
                    }

                    if (!isOk)
                        this.Disconnect();
//addition end

                    throw new SocketException();
                }
            }
```

This appears to have solved my issue.

**Comment by jchristn** [comment]
Hi @IanPNewson do you know if this will work across the supported frameworks, i.e. .NET Framework, .NET Core, .NET 5/6?  I like the approach; the library is pretty blindly throwing a ```SocketException``` and this kind of cleanup could be very useful if it works across the supported frameworks.

**Comment by IanPNewson** [comment]
@jchristn Sorry for delay, I only just saw this.

I think this should work in everything except .net standard prior to v2. I've only personally tested and used it in .net 5 and 6 though.

**Comment by jchristn** [comment]
Hi @IanPNewson I'm very sorry for the delay in getting this added to the package.  100% my fault.  It's in there now in v2.6.0.8, and I added you to the README.  Thank you so much for your contribution!

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.6.0.8
Commit: https://github.com/jchristn/SuperSimpleTcp/commit/041b57bbf1d9578341d11055b09602cc4fe72eab
