### ISSUE TITLE
Issue in the ip and port of client.

### ISSUE THREAD

**Issue by samuxxz** [jchristn/SuperSimpleTcp#133]
I have a problem showing the ip address and port of the client. I have no idea why System.Net.Sockets.Socket/TcpClient appears. When I put e.IpPort the following exception is shown. 
Exception:
![imagen](https://user-images.githubusercontent.com/75233391/160246898-db886a97-1826-4806-9a63-186f2d915414.png)

Issue:
![imagen](https://user-images.githubusercontent.com/75233391/160246917-8f21d0ec-1bb4-46d9-a2e5-ca97c7ef476f.png)

**Comment by jchristn** [comment]
Hi, the event arguments are of type aConnectionEventArgs, not TcpClient.

**Comment by samuxxz** [comment]
Thanks!
