### ISSUE TITLE
Add byte array option for pfx certificate loading in client/server constructors-and-factories.

### ISSUE THREAD

**Issue by WTechnologyDevelopers** [jchristn/SuperSimpleTcp#143]
## Foreword
I know that this update is a bit small for it's size, but the functionality that this small update gives is a lot, I know that this update would help people that are in my position in related to exposing pfx certificates to common users, and the system.

## Problem
Sometimes we don't want to expose our **pfx** certificate to the outside system, becuase it contains the private key to decrypting our network traffic / other elements such as files, by having the pfx certificate as an embedded resource within the program itself helps also with making the program more compact, and portable, this is currently not possible because all of the "constructors-and-factories" only accepts **string pfxCertFilename** as input.

## Solution
Since this project is using the **X509Certificate2** class to define the pfx certificate, a whole new constructor of both SimpleTcpServer, SimpleTcpClient classes can be created with the following inputs **public SimpleTcpServer(string ipPort, bool ssl, byte[] pfxCertFile, string pfxPassword)**, and for the client **public SimpleTcpClient(string serverIpOrHostname, int port, bool ssl, byte[] pfxCertFile, string pfxPassword) : this(serverIpOrHostname, port)**.

(I have changed the variable name "pfxCertFilename", because it technically now doesn't contain the file name, but the file itself.).

**Comment by jchristn** [comment]
Hi @WTechnologyDevelopers excellent suggestion, I just pushed a version that incorporates this on both client and server.  Could you give it a try?

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/2.6.1.1
Commit: https://github.com/jchristn/SuperSimpleTcp/commit/5c1f49e2c758c42a7634abb80cc60eae58fb88a6

**Comment by WTechnologyDevelopers** [comment]
Hey @jchristn! We have been drafting our own version of the SuperSimpleTCP library which fulfill the need that we were looking for, and we will compare your new version to the one we made, we can send to the version we have made, if needed. 

We will start testing the new version immediately, and report back if it works as intended! We all thank you for the fast response to our issue.

**Comment by jchristn** [comment]
I believe this is resolved, please re-open if that's not the case.
