### ISSUE TITLE
Keep alive values

### ISSUE THREAD

**Issue by CetinOzdil** [jchristn/SuperSimpleTcp#150]
https://github.com/jchristn/SuperSimpleTcp/blob/5c4bfbef56dd7a5a2e437f17ac62450f26feb3bf/src/SuperSimpleTcp/SimpleTcpClient.cs#L1092

https://github.com/jchristn/SuperSimpleTcp/blob/5c4bfbef56dd7a5a2e437f17ac62450f26feb3bf/src/SuperSimpleTcp/SimpleTcpClient.cs#L1095

As far as I remember timeout and interval values should be in milliseconds for .NET Framework,

**Comment by jchristn** [comment]
Great catch.  Will amend this!  https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint.settcpkeepalive?view=netframework-4.6.2

**Comment by jchristn** [comment]
Added fix in v3.0.0.1

NuGet: https://www.nuget.org/packages/SuperSimpleTcp/3.0.0.1
Commit: https://github.com/jchristn/SuperSimpleTcp/commit/52ba8d1aaea486a9599ac71e2aab3de7e8df1041

Please re-open if any issues and thank you for your contribution!
