### ISSUE TITLE
Send(); fails on Windows 8/8.1

### ISSUE THREAD

**Issue by aaleaf** [jchristn/SuperSimpleTcp#157]
Error message: System.Reflection.TargetInvocationException: Exception was thrown by the target of invocation.
**System.NullReferenceException**
    TCP.SimpleTcpClient.Send(Byte[]  )
    TCP.SimpleTcpClient.Send(String  )

my application works fine on windows 10 but throws this exception on some windows 8/8.1 users, is this because obfuscated code?

**Comment by jchristn** [comment]
Hi, sorry for the delay.  Could you provide details/steps/code to reproduce?

**Comment by jchristn** [comment]
Please re-open if you can provide details/steps to reproduce
