### ISSUE TITLE
NoDelay option for listener

### ISSUE THREAD

**Issue by QTPah** [jchristn/SuperSimpleTcp#180]
While i can disable the nagle algorithm on the client side with `client.Settings.NoDelay = true` it's not possible on the listener. In the default C# TCP library the option is accessible through `listener.Server.DoDelay` and for client `client.NoDelay`. Please add the `NoDelay` setting for the listener too.

**Comment by jchristn** [comment]
Thanks for catching this.  Just published v3.0.9 here https://www.nuget.org/packages/SuperSimpleTcp/3.0.9 and the commit is here https://github.com/jchristn/SuperSimpleTcp/commit/8d73e2ff1b08a0981eb9f425af3e3f1ddea7093a.  Also added you to the README!
