### ISSUE TITLE
event DataReceived run after get (enter) char at end

### ISSUE THREAD

**Issue by mzelecom** [jchristn/SuperSimpleTcp#91]
hi.
how can i config server to raised DataReceived event when data has (enter) at the end of strings data?
my client is andrid and data change to base64 string .
thanks

**Comment by jchristn** [comment]
Hi @mzelecom you can't.  SimpleTcp will simply read from the socket and fire the event with whatever it gets.  There is no message framing.

You are welcome to modify the DataReceiver method in the client/server to examine the data it's read and fire the event when it suits your needs.
