### ISSUE TITLE
data receiver start very slow

### ISSUE THREAD

**Issue by mzelecom** [jchristn/SuperSimpleTcp#93]
hi.
i test SuperSimpleTcp for my game server .
when about 50 client or more want to connect at the same time .server not response fast .
client connect very quickly but couldnt send data to server .and after about 60 sec all data comes in DataReceived event.
i log your example project and in log function show that start data receiver is very slow.
is it bug?
thanks

**Comment by jchristn** [comment]
Hi @mzelecom this is not a bug.  Each connection is accepted in a synchronous manner, and when the connection is being accepted, it starts a background task to receive data from that connection (along with some other housekeeping items).  Those background tasks and their prioritization are managed by the OS.  I've found that most TCP and messaging libraries face the common issue of connection establishment being slow (especially under load) and steady-state (lots of already connected clients exchanging data) being just fine.  If you can point to specific methods/invocations that are slow that could be optimized I'd love a PR on it.  Thanks, Joel

**Comment by mzelecom** [comment]
i used mina.net framework  (https://github.com/longshine/Mina.NET)
it is very good but i dont know why server not accept new clients after some times.(no error occur).and couldnt solve the problem.
supersocket framework (https://github.com/kerryjiang/SuperSocket) also very good but after sometimes it become very slow.
my game server has 400 client connected at the same time.when i start server again 400 client must connected at the same time .so i need very fast at starting recive data.
you can also check (https://github.com/chronoxor/CSharpServer)
thanks

**Comment by jchristn** [comment]
Thanks - yes I'm aware of those. Please let me know if you find a specific bug. Cheers
