### ISSUE TITLE
Support for constructor that binds TcpClient with specified local endpoint

### ISSUE THREAD

**Issue by abrasat** [jchristn/SuperSimpleTcp#97]
Thanks for the very useful library.

Could you please extend the library with the support of the TcpClient constructor that allows the binding to a local endpoint?
It would be useful when using the library in an application that has to handle several network interfaces on the same PC.
[https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.-ctor?view=net-5.0#System_Net_Sockets_TcpClient__ctor_System_Net_IPEndPoint_](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.-ctor?view=net-5.0#System_Net_Sockets_TcpClient__ctor_System_Net_IPEndPoint_)

Does the library support several SimpleTcpClient instances running in parallel, each of them connecting to a different TCP server? Do you eventually have a code sample for this scenario?

**Comment by kbpruner** [comment]
@abrasat, Have you considered an array holding the client connections. Then using the sender and Equals to match to the correct interface from the array inside events. I'm using this method to support multiple open channels at once.
